language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "lorenzoval"
    token:
      secure: "93fa8c8a74bd2007706ffcc7522e43707c37addf"

script:
- ant build
- sonar-scanner

